import XCTest

final class ReaderUITests: XCTestCase {
    func testReadSaveAndSearchWithoutDictionary() {
        continueAfterFailure = false
        let app = XCUIApplication()
        app.launch()
        let editor = app.textViews.firstMatch
        XCTAssertTrue(editor.waitForExistence(timeout: 10))
        let readerScreenshot = XCTAttachment(screenshot: app.screenshot())
        readerScreenshot.name = "Reader screen"
        readerScreenshot.lifetime = .keepAlways
        add(readerScreenshot)
        editor.tap()
        editor.typeText("Japanese reading test")
        app.buttons["openPassage"].tap()
        XCTAssertEqual(app.switches["autoSavePassages"].value as? String, "0")
        app.tabBars.buttons["Library"].tap()
        XCTAssertTrue(app.staticTexts["emptyLibrary"].waitForExistence(timeout: 10))
        app.terminate()
        app.launch()
        XCTAssertEqual(app.textViews["passageEditor"].value as? String, "")
        app.textViews["passageEditor"].tap()
        app.textViews["passageEditor"].typeText("Japanese reading test")
        app.buttons["openPassage"].tap()
        app.buttons["Save"].tap()
        app.tabBars.buttons["Library"].tap()
        XCTAssertTrue(app.buttons["Japanese reading test"].waitForExistence(timeout: 15))
        app.terminate()
        app.launch()
        app.tabBars.buttons["Library"].tap()
        XCTAssertTrue(app.buttons["Japanese reading test"].waitForExistence(timeout: 15))
        XCTAssertTrue(app.buttons["Export saved texts"].exists)
        app.buttons["Japanese reading test"].swipeLeft()
        app.buttons["Delete"].firstMatch.tap()
        XCTAssertTrue(app.staticTexts["emptyLibrary"].waitForExistence(timeout: 10))
        app.buttons["Undo delete"].tap()
        XCTAssertTrue(app.buttons["Japanese reading test"].waitForExistence(timeout: 10))
        app.buttons["Delete all saved passages"].tap()
        app.buttons["Delete all"].tap()
        XCTAssertTrue(app.staticTexts["emptyLibrary"].waitForExistence(timeout: 10))
        app.terminate(); app.launch()
        app.tabBars.buttons["Library"].tap()
        XCTAssertTrue(app.staticTexts["emptyLibrary"].waitForExistence(timeout: 10))
        app.tabBars.buttons["Read"].tap()
        // SwiftUI exposes the entire labelled row as a switch. Its center is
        // the label; target the visible switch control at the trailing edge.
        app.switches["autoSavePassages"].coordinate(withNormalizedOffset: CGVector(dx: 0.93, dy: 0.5)).tap()
        XCTAssertEqual(app.switches["autoSavePassages"].value as? String, "1")
        app.textViews["passageEditor"].tap()
        app.textViews["passageEditor"].typeText("Automatically saved passage")
        app.buttons["openPassage"].tap()
        app.tabBars.buttons["Library"].tap()
        XCTAssertTrue(app.buttons["Automatically saved passage"].waitForExistence(timeout: 10))
        app.terminate(); app.launch()
        XCTAssertEqual(app.switches["autoSavePassages"].value as? String, "1")
        app.switches["autoSavePassages"].coordinate(withNormalizedOffset: CGVector(dx: 0.93, dy: 0.5)).tap()
        app.textViews["passageEditor"].tap()
        app.textViews["passageEditor"].typeText("Keep this temporary")
        app.buttons["openPassage"].tap()
        app.tabBars.buttons["Library"].tap()
        XCTAssertTrue(app.buttons["Automatically saved passage"].waitForExistence(timeout: 10))
        XCTAssertFalse(app.buttons["Keep this temporary"].exists)
        app.terminate(); app.launch()
        XCTAssertEqual(app.switches["autoSavePassages"].value as? String, "0")
        app.tabBars.buttons["Look up"].tap()
        let search = app.textFields["Search Japanese…"]
        search.tap(); search.typeText("test")
        app.buttons["Search dictionaries"].tap()
        XCTAssertTrue(app.staticTexts["Add the dictionaries folder in Library first."].waitForExistence(timeout: 10))
        let screenshot = XCTAttachment(screenshot: app.screenshot())
        screenshot.lifetime = .keepAlways
        add(screenshot)
    }
}
